version: '3'
services:

  redis:
    image: sickp/alpine-redis:3.2.2
    ports:
        - "${REDIS_PORT}:6379"
    volumes:
      - ./.docker/redisdata/:/data
    networks:
      - local

  workspace:
    image: lucasmesquitaborges/laravel
    container_name: workspace
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: workspace
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    depends_on:
      - redis
      - db
      - nginx
    volumes:
      - ./:/var/www/html
    networks:
      - local

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/conf.d/log:/var/log/nginx
    networks:
      - local

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  mysqldata:
    driver: local
